### ISSUE TITLE
竟然没有问题，我提一个，最后那个需要配置config.yaml说的不清楚，能给个例子么？另外，不太明白OmDet运行起来后，OmAgent是怎么连上OmDet的

### ISSUE THREAD

**Issue by chenxu126** [om-ai-lab/OmAgent#2]
竟然没有问题，我提一个，最后那个需要配置config.yaml说的不清楚，能给个例子么？另外，不太明白OmDet运行起来后，OmAgent是怎么连上OmDet的

**Comment by XeonHis** [comment]
# config.yml配置
config.yml是用来配置workflows中的一些配置项，例如一些连接LLM/Vector DB的信息。
例如```workflows/general/llms/gpt4o.json```中的```$<custom_openai_key::openai_api_key>```，custom_openai_key就是一个配置项的名称。
以下是一个config.yml的示例
```yaml
bing_api_key: your_bing_api_key
custom_openai_endpoint: http://xxx.com/v1
custom_openai_key: your_custom_openai_key
ovd_endpoint: http://xxx/inf_predict
ovd_model_id: OmDet-Turbo_tiny_SWIN_T
milvus_host_url: your_milvus_host_url
port: 19530
alias: default
```
# OmDet运行
OmAgent和OmDet的运行进行了解耦，这两者是通过http请求的方式进行联通的。通过将OmDet启动成一个[API服务的方式](https://github.com/om-ai-lab/OmDet/tree/main?tab=readme-ov-file#run-as-a-api-server)，向外暴露一个OmDet调用接口的方式让OmAgent进行调用。
